[package]
org = "wso2"
name = "weatherAlerts"
version = "0.1.0"
distribution = "2201.8.2"

[build-options]
observabilityIncluded = true

[persist]
datastore = "mysql"
module = "weatherAlerts.store"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.0"

